CREATE TABLE [B_Ergebnisse_A] (
  [ID_Gebäudeteil] AUTOINCREMENT,
  [Bezeichnung] VARCHAR (255),
  [Straße] VARCHAR (255),
  [Gebäudeteil] VARCHAR (255),
  [Typ aus NHK-Typen] LONG,
  [BGF] DOUBLE,
  [BRI] DOUBLE,
  [Baujahr_real] DATETIME,
  [Baujahr_mod] DATETIME,
  [gewöhnliche Nutzungsdauer] LONG,
  [geschätze Nutzungsdauer] LONG,
  [Ausstattung] VARCHAR (255),
  [Wert von] DOUBLE,
  [Wert bis] DOUBLE,
  [Euro je BGF] DOUBLE,
  [Wert NHK x BGF] DOUBLE,
  [Index] DOUBLE,
  [hochgerechneter Wert] DOUBLE,
  [Baunebenkosten] LONG,
  [Baunebenkosten €] DOUBLE,
  [Herstellungskosten1] DOUBLE,
  [Neubauwert_ab_2000] DOUBLE,
  [Index 2000] DOUBLE,
  [Herstellungskosten2] DOUBLE,
  [berücksichtigtes Baujahr] DATETIME,
  [Nutzungsdauer] LONG,
  [Bewertung abgeschlossen] DATETIME,
  [Index_manuell] DOUBLE,
  [Versicherungswert] CURRENCY
)
