dbMemo "SQL" ="INSERT INTO Archiv_Mietberechnungen ( Planjahr, Betrieb, BereichNr, BereichName,"
    " Bezeichnung, ID, Kostenart, Betrag, sort, Bruttogrundfläche, [Text], datum )\015"
    "\012SELECT NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Haushaltsjahr, NK_enstand"
    "en_ohne_Vorauszahlungen_DS_suchen.Betrieb, NK_enstanden_ohne_Vorauszahlungen_DS_"
    "suchen.BereichNr, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.BereichName, NK_en"
    "standen_ohne_Vorauszahlungen_DS_suchen.Bezeichnung, NK_enstanden_ohne_Vorauszahl"
    "ungen_DS_suchen.M_Objekte.ID, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Kosten"
    "art, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Betrag, NK_enstanden_ohne_Vorau"
    "szahlungen_DS_suchen.sort, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Bruttogru"
    "ndfläche, First(NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Text) AS [ErsterWert"
    " von Text], Archiv_Mietberechnungen.datum\015\012FROM NK_enstanden_ohne_Vorausza"
    "hlungen_DS_suchen LEFT JOIN Archiv_Mietberechnungen ON NK_enstanden_ohne_Vorausz"
    "ahlungen_DS_suchen.Text = Archiv_Mietberechnungen.Text\015\012GROUP BY NK_enstan"
    "den_ohne_Vorauszahlungen_DS_suchen.Haushaltsjahr, NK_enstanden_ohne_Vorauszahlun"
    "gen_DS_suchen.Betrieb, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.BereichNr, NK"
    "_enstanden_ohne_Vorauszahlungen_DS_suchen.BereichName, NK_enstanden_ohne_Vorausz"
    "ahlungen_DS_suchen.Bezeichnung, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.M_Ob"
    "jekte.ID, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Kostenart, NK_enstanden_oh"
    "ne_Vorauszahlungen_DS_suchen.Betrag, NK_enstanden_ohne_Vorauszahlungen_DS_suchen"
    ".sort, NK_enstanden_ohne_Vorauszahlungen_DS_suchen.Bruttogrundfläche, Archiv_Mie"
    "tberechnungen.datum;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbBoolean "UseTransaction" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbText "SubdatasheetName" ="[Auto]"
Begin
    Begin
        dbText "Name" ="ErsterWert von Text"
        dbInteger "ColumnWidth" ="2520"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
End
