dbMemo "SQL" ="SELECT Plausibilitätsprüfung_Buchungen_2a.Emfpänger, Plausibilitätsprüfung_Buchu"
    "ngen_2a.angelegt, Plausibilitätsprüfung_Buchungen_2a.Verwendungszweck, Plausibil"
    "itätsprüfung_Buchungen_2a.Anordnungsbetrag, Plausibilitätsprüfung_Buchungen_2a.E"
    "inzelbetrag, Plausibilitätsprüfung_Buchungen_2b.[Kennummer], \"Buchung auf nicht"
    " verwaltetes Objekt / keine Kostenstelle im Buchungssatz (korrupter Satz)\" AS ["
    "Text]\015\012FROM Plausibilitätsprüfung_Buchungen_2a LEFT JOIN Plausibilitätsprü"
    "fung_Buchungen_2b ON Plausibilitätsprüfung_Buchungen_2a.[ID aus Kostenstellen] ="
    " Plausibilitätsprüfung_Buchungen_2b.[Kennummer]\015\012WHERE (((Plausibilitätspr"
    "üfung_Buchungen_2b.[Kennummer]) Is Null))\015\012\015\012UNION SELECT [Anrede] &"
    " \", \" & [Name, Vorname] AS Emfpänger, A_Buchungen.angelegt, A_Buchungen.Verwen"
    "dungszweck, A_Buchungen.Betrag AS Anordnungsbetra, Sum(A_Buchungen_Aufteilung_au"
    "f_Kostenstellen.Betrag) AS [Betrag aufgeteilt], A_Buchungen.Betrag-Sum(A_Buchung"
    "en_Aufteilung_auf_Kostenstellen.Betrag) AS Differenz, \"Gesamtbetrag falsch auft"
    "geteilt\" AS [Text]\015\012FROM (A_Buchungen LEFT JOIN A_Empfänger ON A_Buchunge"
    "n.[ID Empfänger] = A_Empfänger.ID) LEFT JOIN A_Buchungen_Aufteilung_auf_Kostenst"
    "ellen ON A_Buchungen.ID = A_Buchungen_Aufteilung_auf_Kostenstellen.[ID aus Buchu"
    "ngen]\015\012GROUP BY [Anrede] & \", \" & [Name, Vorname], A_Buchungen.angelegt,"
    " A_Buchungen.Verwendungszweck, A_Buchungen.Betrag, \"Gesamtbetrag falsch aufgete"
    "ilt\", A_Buchungen.ID, A_Buchungen.Haushaltsjahr\015\012HAVING (((A_Buchungen.Ha"
    "ushaltsjahr)=Year(Now())) AND (([A_Buchungen].[Betrag]-Sum([A_Buchungen_Aufteilu"
    "ng_auf_Kostenstellen].[Betrag]))<-0.009)) OR (((A_Buchungen.Haushaltsjahr)=Year("
    "Now())) AND (([A_Buchungen].[Betrag]-Sum([A_Buchungen_Aufteilung_auf_Kostenstell"
    "en].[Betrag]))>0.009))\015\012\015\012UNION SELECT A_Buchungen.[ID Empfänger], A"
    "_Buchungen.angelegt, A_Buchungen.Verwendungszweck, A_Buchungen.Betrag, Null AS A"
    "O_Betrag, Null AS aufgeteilt, \"Kein Empfänger angegeben!\" AS [Text]\015\012FRO"
    "M A_Buchungen LEFT JOIN A_Empfänger ON A_Buchungen.[ID Empfänger] = A_Empfänger."
    "ID\015\012WHERE (((A_Buchungen.[ID Empfänger]) Is Null))\015\012\015\012UNION SE"
    "LECT A_Buchungen.[ID Nebenkostenart], A_Buchungen.angelegt, A_Buchungen.Verwendu"
    "ngszweck, A_Buchungen.Betrag, Null AS AO_Betrag, Null AS aufgeteilt, \"Keine Kos"
    "tenart angegeben!\" AS [Text]\015\012FROM A_Buchungen LEFT JOIN A_Empfänger ON A"
    "_Buchungen.[ID Empfänger] = A_Empfänger.ID\015\012WHERE (((A_Buchungen.[ID Neben"
    "kostenart]) Is Null))\015\012\015\012UNION SELECT A_Empfänger.[Name, Vorname], A"
    "_Buchungen.angelegt, A_Buchungen.Verwendungszweck, A_Buchungen.Betrag, A_Buchung"
    "en_Aufteilung_auf_Kostenstellen.Betrag, M_Kostenstellen.Kostenstelle, \"Kein Bet"
    "rag oder unnötiger Betrag aufgeteilt!\" AS [Text]\015\012FROM ((A_Buchungen_Auft"
    "eilung_auf_Kostenstellen LEFT JOIN A_Buchungen ON A_Buchungen_Aufteilung_auf_Kos"
    "tenstellen.[ID aus Buchungen] = A_Buchungen.ID) LEFT JOIN A_Empfänger ON A_Buchu"
    "ngen.[ID Empfänger] = A_Empfänger.ID) LEFT JOIN M_Kostenstellen ON A_Buchungen_A"
    "ufteilung_auf_Kostenstellen.[ID aus Kostenstellen] = M_Kostenstellen.Kennummer\015"
    "\012WHERE (((A_Buchungen_Aufteilung_auf_Kostenstellen.Betrag) Is Null Or (A_Buch"
    "ungen_Aufteilung_auf_Kostenstellen.Betrag)=0))\015\012\015\012UNION SELECT A_Buc"
    "hungen.[ID Sachbearbeiter], A_Buchungen.angelegt, A_Buchungen.Verwendungszweck, "
    "A_Buchungen.Betrag, Null AS AO_Betrag, Null AS aufgeteilt, \"Kein Sachberarbeite"
    "r angegeben!\" AS [Text]\015\012FROM A_Buchungen LEFT JOIN A_Empfänger ON A_Buch"
    "ungen.[ID Empfänger] = A_Empfänger.ID\015\012WHERE (((A_Buchungen.[ID Sachbearbe"
    "iter]) Is Null))\015\012\015\012UNION SELECT A_Buchungen.[ID Fälligkeiten], A_Bu"
    "chungen.angelegt, A_Buchungen.Verwendungszweck, A_Buchungen.Betrag, Null AS AO_B"
    "etrag, Null AS aufgeteilt, \"Kein Zahlungszyklus angegeben!\" AS [Text]\015\012F"
    "ROM A_Buchungen LEFT JOIN A_Empfänger ON A_Buchungen.[ID Empfänger] = A_Empfänge"
    "r.ID\015\012WHERE (((A_Buchungen.[ID Fälligkeiten]) Is Null))\015\012\015\012UNI"
    "ON SELECT DISTINCTROW A_Empfänger.[Name, Vorname], A_Buchungen.angelegt, A_Buchu"
    "ngen.Verwendungszweck, A_Buchungen.Betrag, A_Buchungen_Aufteilung_auf_Kostenstel"
    "len.Betrag, M_Kostenstellen.Kostenstelle, \"Kostenst. durfte am \" & Format([ang"
    "elegt],\"dd/mm/yyyy\") & IIf([angelegt]<[Buch_Zeitr_Start],\" noch nicht \",\" n"
    "icht mehr \") & \"bebucht werden.\" AS [Text]\015\012FROM ((A_Buchungen_Aufteilu"
    "ng_auf_Kostenstellen INNER JOIN A_Buchungen ON A_Buchungen_Aufteilung_auf_Kosten"
    "stellen.[ID aus Buchungen] = A_Buchungen.ID) INNER JOIN A_Empfänger ON A_Buchung"
    "en.[ID Empfänger] = A_Empfänger.ID) INNER JOIN (M_Kostenstellen INNER JOIN Plaus"
    "ibilitätsprüfung_Zeitsp_Kostellen ON M_Kostenstellen.Kennummer = Plausibilitätsp"
    "rüfung_Zeitsp_Kostellen.Kennummer) ON A_Buchungen_Aufteilung_auf_Kostenstellen.["
    "ID aus Kostenstellen] = M_Kostenstellen.Kennummer\015\012WHERE ((([angelegt]<[Bu"
    "ch_Zeitr_Start] Or [angelegt]>[Buch_Zeitr_Ende])=True));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbText "SubdatasheetName" ="[Auto]"
Begin
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2a.Einzelbetrag"
        dbInteger "ColumnWidth" ="1826"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2a.angelegt"
        dbInteger "ColumnWidth" ="2940"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2a.Emfpänger"
        dbInteger "ColumnWidth" ="4575"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2a.Verwendungszweck"
        dbInteger "ColumnWidth" ="4305"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2a.Anordnungsbetrag"
        dbInteger "ColumnWidth" ="1905"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Text"
        dbInteger "ColumnWidth" ="11546"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
    Begin
        dbText "Name" ="Plausibilitätsprüfung_Buchungen_2b.[Kennummer]"
        dbLong "AggregateType" ="-1"
    End
End
