Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Private Sub Report_Open(Cancel As Integer)
' Bei Filter auf einen SB Summeneinblendung der voraussichtlichen Kosten andrucken,
' Bei Filter auf alle SB Summeneinblendung der tatsächlichen Kosten andrucken,
' Telefonat mit H. Kania am 25.10.2017
10  If lng_ID_SB_Min = lng_ID_SB_Max Then

80  Else

150 End If

End Sub
